Feature readme
DBenMoshe/contrast-ratio-repo pull request #14
Opened 2022-08-07 14:14 UTC by Okibe00

Modified readme file

2022-08-07 21:15 UTC, AndreyDmitriev39r requested changes

2022-08-08 06:07 UTC, Okibe00 commented on README.md
> +The app evaluates the readability of page content by comparing the text color with the background color,this is done  by calculating the aspect ratio and comparing the result to w3c provided standard
i agree its a typo

2022-08-08 11:31 UTC, AndreyDmitriev39r commented
@jdwilkin4 I was ready to merge it couple of hours ago, but we chatted a little in discord, and decided, that it will be good opportunity for @DBenMoshe to review PR for the first time.

2022-08-09 03:52 UTC, DBenMoshe approved these changes
Covered all everything listed! Good work

2022-08-09 03:56 UTC, AndreyDmitriev39r approved these changes

2022-08-09 04:15 UTC, merged